### PR TITLE
CI: Update macOS Runner (Latest)

### PR DESCRIPTION
**Pull request by ax3l**
The old `macos-11` image is now removed. Update to running release `macos-latest`.

- [x] `picsar_tables` test: some numerical values vary on near-machine precision but compare without an epsilon

### CODE REVIEW

**Comment by ax3l** [comment]
@lucafedeli88 the table test seems to need a tolerance review on the last significant digits. Can you help with this? :pray:

**Review by lucafedeli88 — COMMENTED** [review]
Hi @ax3l ,
thanks for this PR! 
Precision for the failing test (`test_picsar_tables.cpp`) is set by these two variables
```
//Tolerance for double precision calculations
const double double_tolerance = 1.0e-12;

//Tolerance for single precision calculations
const float float_tolerance = 1.0e-5;
```

We may try to increase the tolerance by a small factor (e.g., 2 or 5) and see if the tests pass.
I can do that if you want!
Besides of that, the PR looks good to me: as soon as the tests pass we can merge it.

**Comment by ax3l** [comment]
Hi @lucafedeli88,

> We may try to increase the tolerance by a small factor (e.g., 2 or 5) and see if the tests pass.
I can do that if you want!

Thanks a lot - I pushed a few updates, but happy if you can take it over for the tolerances :)

**Comment by ax3l** [comment]
Ah, the tolerances are not used in the tests that actually fail:
- `BOOST_CHECK_EQUAL` for the `linear_function`

**Review by lucafedeli88 — APPROVED** [review]
Oh, sorry! I didn't know that the failing test actually used `BOOST_CHECK_EQUAL`.
I think that your change makes sense here.
Thanks for this PR!

**Pull request merged**
